name: listviewgroupingsample
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  bloc: ^6.0.1
  cupertino_icons: ^0.1.3
  equatable: ^1.2.3
  flutter_bloc: ^6.0.1
  get_it: ^4.0.4
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/mock/list.json
